name: prettier

on:
  push:
  pull_request:

jobs:
  run_eslint:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install
      - name: Prettier#check
        run: yarn run check
